In [0]:
from sklearn.datasets import load_iris

In [2]:
import numpy as np
import keras
np.random.seed(10)

Using TensorFlow backend.


In [4]:
iris = load_iris()
print(iris.keys())


dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [0]:
x = iris['data']
y = iris['target']
name = iris['target_names']
feature = iris['feature_names']

In [0]:
isample = np.random.randint(len(y),size =(5))

In [7]:
print(x.shape,y.shape)

(150, 4) (150,)


In [8]:
print(x[isample],y[isample])

[[4.9 3.1 1.5 0.1]
 [7.2 3.2 6.  1.8]
 [5.7 4.4 1.5 0.4]
 [5.6 2.9 3.6 1.3]
 [5.7 2.5 5.  2. ]] [0 2 0 1 2]


In [0]:
Ny = len(np.unique(y))
#one hot encoding
y = keras.utils.to_categorical(y[:],num_classes=Ny)

In [10]:
print("X : ",x[isample,:])
print("Y : ",y[isample])

X :  [[4.9 3.1 1.5 0.1]
 [7.2 3.2 6.  1.8]
 [5.7 4.4 1.5 0.4]
 [5.6 2.9 3.6 1.3]
 [5.7 2.5 5.  2. ]]
Y :  [[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size =0.2,random_state =1)
print(X_train.shape)
print(X_test.shape)

(120, 4)
(30, 4)


In [15]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
scalar.fit(X_train) #computing mean and variance of the given data
X_train = scalar.transform(X_train)
X_test = scalar.transform(X_test)
print(X_train)

[[ 0.31553662 -0.04578885  0.44767531  0.23380268]
 [ 2.2449325  -0.04578885  1.29769171  1.39742892]
 [-0.2873996  -1.24028061  0.05100098 -0.15407273]
 [ 0.67729835 -0.52358555  1.01435291  1.13884531]
 [-0.04622511 -0.52358555  0.73101411  1.52672073]
 [-0.64916132  1.62649961 -1.30902526 -1.31769898]
 [-0.40798684 -1.71807731  0.10766874  0.10451088]
 [-0.76974857  0.90980456 -1.36569302 -1.31769898]
 [ 0.79788559 -0.52358555  0.44767531  0.36309449]
 [ 1.03906007 -1.24028061  1.12768843  0.7509699 ]
 [ 1.15964732 -0.04578885  0.95768515  1.13884531]
 [-0.89033581  1.14870291 -1.36569302 -1.18840717]
 [ 0.19494938 -1.95697567  0.67434635  0.36309449]
 [ 0.5567111  -0.2846872   1.01435291  0.7509699 ]
 [ 0.91847283 -0.2846872   0.44767531  0.10451088]
 [ 2.2449325  -1.00138226  1.75103379  1.39742892]
 [-0.16681235  1.86539796 -1.19568974 -1.18840717]
 [-1.01092305  1.38760126 -1.36569302 -1.31769898]
 [-1.25209754 -0.04578885 -1.36569302 -1.18840717]
 [-0.76974857 -0.76248391  0.05

In [18]:
#training data
addicol = lambda x: np.concatenate((x, np.ones((x.shape[0],1))),axis=1)
Ns,Nx = X_train.shape
XX = addicol(X_train)
YY = Y_train
print(YY.shape)
w = np.linalg.inv(XX.T.dot(XX)).dot(XX.T.dot(YY))
print(w)
def evaluate(X,W,Yd):
  x = addicol(X)
  yd = np.argmax(Yd,axis =1)
  y = np.argmax(x.dot(W),axis =1)
  print("CM:")
  print(confusion_matrix(yd,y))
evaluate(X_train,w,Y_train)
evaluate(X_test,w,Y_test)

(120, 3)
[[ 0.06062508  0.05806364 -0.11868873]
 [ 0.10258458 -0.21112954  0.10854496]
 [-0.4070331   0.22897614  0.17805695]
 [-0.03856453 -0.30252108  0.34108561]
 [ 0.325       0.30833333  0.36666667]]
CM:
[[39  0  0]
 [ 0 22 15]
 [ 0  4 40]]
CM:
[[11  0  0]
 [ 0  6  7]
 [ 0  0  6]]
